evmate_set_current:
  fields:
    evse_id:
      example: "1"
      default: 1
      required: true
      selector:
        number:
          min: 1
          max: 10
    current:
      example: "6"
      default: 6
      required: true
      selector:
        number:
          min: 1
          max: 16